import moment from "moment";
import { describe, expect, it } from "vitest";
import { dateGroupLabel, isUniqueNoteName, parseDatetime, stripFrontmatter } from "../src/view";

describe("parseDatetime", () => {
	it("parses a quoted string with seconds at face value, in local time", () => {
		const date = parseDatetime("2026-09-25T16:20:00");
		expect(date?.isValid()).toBe(true);
		expect(date?.format("YYYY-MM-DD HH:mm:ss")).toBe("2026-09-25 16:20:00");
	});

	it("parses a quoted string without seconds", () => {
		const date = parseDatetime("2026-09-25T16:20");
		expect(date?.format("YYYY-MM-DD HH:mm")).toBe("2026-09-25 16:20");
	});

	it("parses a quoted date-only string as local midnight", () => {
		const date = parseDatetime("2026-09-25");
		expect(date?.format("YYYY-MM-DD HH:mm:ss")).toBe("2026-09-25 00:00:00");
	});

	it("returns null for a string that doesn't match any accepted format", () => {
		expect(parseDatetime("not a date")).toBeNull();
		expect(parseDatetime("25/09/2026")).toBeNull();
	});

	it("forces local midnight for a date-only value auto-cast to a native Date (unquoted YAML)", () => {
		// A bare "date: 2026-09-25" resolves to Date.UTC(2026, 8, 25) — always
		// exactly UTC midnight when the source text carries no time-of-day.
		// Asserting on the *local* hour/minute/second (rather than a specific
		// UTC offset) keeps this test's result the same on any machine,
		// regardless of its configured timezone.
		const date = parseDatetime(new Date(Date.UTC(2026, 8, 25, 0, 0, 0)));
		expect(date?.isValid()).toBe(true);
		expect(date?.hour()).toBe(0);
		expect(date?.minute()).toBe(0);
		expect(date?.second()).toBe(0);
	});

	it("preserves a genuinely combined date+time value auto-cast to a native Date, instead of discarding it to midnight", () => {
		// Verified via its UTC time-of-day (not a specific local hour) so this
		// test's expectation doesn't depend on the machine's timezone — the
		// documented residual limitation is that this is interpreted as UTC,
		// not local, which this assertion reflects rather than papers over.
		const date = parseDatetime(new Date(Date.UTC(2026, 8, 25, 16, 20, 0)));
		expect(date?.isValid()).toBe(true);
		expect(date?.clone().utc().format("HH:mm:ss")).toBe("16:20:00");
	});

	it("returns null for an unparseable value", () => {
		expect(parseDatetime(new Date(NaN))).toBeNull();
	});

	it("rejects non-string, non-Date values instead of guessing at them", () => {
		expect(parseDatetime(2026)).toBeNull();
		expect(parseDatetime(["2026-09-25"])).toBeNull();
		expect(parseDatetime(null)).toBeNull();
		expect(parseDatetime(undefined)).toBeNull();
	});
});

describe("dateGroupLabel", () => {
	// A fixed Wednesday reference, itself derived from "now" so the test still
	// passes no matter which real day it's run on — every case below is an
	// offset *from* this reference, not an absolute calendar date, so the
	// result stays correct regardless of what week it actually is.
	const now = moment().day(3).startOf("day").hour(12);

	it("labels today as Today", () => {
		expect(dateGroupLabel(now.clone(), now)).toBe("Today");
	});

	it("folds a future-dated note into Today rather than inventing a fifth label", () => {
		expect(dateGroupLabel(now.clone().add(5, "days"), now)).toBe("Today");
	});

	it("labels exactly one day back as Yesterday", () => {
		expect(dateGroupLabel(now.clone().subtract(1, "day"), now)).toBe("Yesterday");
	});

	it("labels an earlier day in the same week as This week", () => {
		expect(dateGroupLabel(now.clone().subtract(2, "days"), now)).toBe("This week");
	});

	it("labels the day right before the start of this week as Older", () => {
		const dayBeforeWeekStart = now.clone().startOf("week").subtract(1, "day");
		expect(dateGroupLabel(dayBeforeWeekStart, now)).toBe("Older");
	});

	it("labels a note from weeks ago as Older", () => {
		expect(dateGroupLabel(now.clone().subtract(3, "weeks"), now)).toBe("Older");
	});
});

describe("isUniqueNoteName", () => {
	it("matches a basename generated by the given format, exactly", () => {
		expect(isUniqueNoteName("202609251620", "YYYYMMDDHHmm")).toBe(true);
	});

	it("does not match a renamed note", () => {
		expect(isUniqueNoteName("My renamed note", "YYYYMMDDHHmm")).toBe(false);
	});

	it("does not match a string of the wrong length for the format (strict parsing)", () => {
		expect(isUniqueNoteName("20260925162000", "YYYYMMDDHHmm")).toBe(false);
	});
});

describe("stripFrontmatter", () => {
	it("removes a normal frontmatter block, leaving only the body", () => {
		const raw = "---\ntimestamp: \"2026-09-25T16:20:00\"\ntags: [a, b]\n---\nBody text.";
		expect(stripFrontmatter(raw)).toBe("Body text.");
	});

	it("removes a completely empty frontmatter block (the regression fixed this session)", () => {
		const raw = "---\n---\nBody text.";
		expect(stripFrontmatter(raw)).toBe("Body text.");
	});

	it("leaves content with no frontmatter block untouched", () => {
		const raw = "Just a body, no frontmatter.";
		expect(stripFrontmatter(raw)).toBe(raw);
	});

	it("handles CRLF line endings", () => {
		const raw = "---\r\ntimestamp: \"2026-09-25T16:20:00\"\r\n---\r\nBody text.";
		expect(stripFrontmatter(raw)).toBe("Body text.");
	});
});
